#!/usr/bin/env bash
#
# Apply the once-per-account bootstrap stack for the AWS demo
# (docs/roadmap/aws-demo-plan.md): the Terraform state bucket, GitHub's OIDC
# trust, the coppice.jwjr.uk hosted zone and the wildcard certificate.
#
# Usually run twice in the lifetime of an account:
#
#   scripts/aws-demo/bootstrap.sh              # create everything, print the
#                                              # nameservers to delegate to
#   ...add the NS records in Linode's DNS manager...
#   scripts/aws-demo/bootstrap.sh --validate   # wait for ACM to issue
#
# Needs credentials that can create IAM roles and an OIDC provider (an account
# administrator), not the federated CI role — that role is a product of this
# stack.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MODULE_DIR="$REPO_ROOT/deploy/aws/bootstrap"
LOCAL_STATE_DIR="$MODULE_DIR/.bootstrap-local"
# Terraform merges any *_override.tf over the module's own blocks, which is the
# only way to swap the backend without editing the committed files.
OVERRIDE_FILE="$MODULE_DIR/zz_local_backend_override.tf"
# Overridable for a fork, matching scripts/aws-demo/lib.sh; the env stack reads
# its bootstrap outputs from the same region and bucket.
REGION="${REGION:-eu-west-2}"
DOMAIN="${DOMAIN:-coppice.jwjr.uk}"
STATE_KEY="bootstrap/terraform.tfstate"

usage() {
  cat <<'EOF'
usage: bootstrap.sh [--validate] [--plan] [--yes]

  --validate  wait for the wildcard ACM certificate to be issued. Only works
              once the `coppice` label is delegated to this zone's nameservers
              in Linode's DNS manager for jwjr.uk.
  --plan      show the plan and stop; changes nothing.
  --yes       skip Terraform's interactive approval.
EOF
}

log() {
  echo "==> $*"
}

die() {
  echo "bootstrap.sh: $*" >&2
  exit 1
}

cleanup() {
  rm -f "$OVERRIDE_FILE"
}

# Whether the state bucket already exists, i.e. whether this account has been
# bootstrapped before. Anything other than a clean "no such bucket" is a
# credentials or ownership problem worth stopping on.
state_bucket_exists() {
  local out status
  set +e
  out="$(aws s3api head-bucket --bucket "$1" --region "$REGION" 2>&1)"
  status=$?
  set -e
  if [ "$status" -eq 0 ]; then
    return 0
  fi
  case "$out" in
  *404* | *"Not Found"*) return 1 ;;
  *) die "cannot inspect s3://$1: $out" ;;
  esac
}

# Point the module at a local state file. Used only for the first apply, where
# the S3 backend cannot exist yet.
write_local_backend_override() {
  mkdir -p "$LOCAL_STATE_DIR"
  cat >"$OVERRIDE_FILE" <<EOF
# Generated by scripts/aws-demo/bootstrap.sh; removed when it exits.
terraform {
  backend "local" {
    path = "$LOCAL_STATE_DIR/bootstrap.tfstate"
  }
}
EOF
}

terraform_init_s3() {
  terraform -chdir="$MODULE_DIR" init "$@" \
    -backend-config="bucket=$state_bucket" \
    -backend-config="key=$STATE_KEY" \
    -backend-config="region=$REGION" \
    -backend-config="use_lockfile=true"
}

validate=false
plan_only=false
auto_approve=false
while [ $# -gt 0 ]; do
  case "$1" in
  --validate)
    validate=true
    shift
    ;;
  --plan)
    plan_only=true
    shift
    ;;
  --yes)
    auto_approve=true
    shift
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  *)
    echo "bootstrap.sh: unknown argument: $1" >&2
    usage >&2
    exit 2
    ;;
  esac
done

command -v terraform >/dev/null 2>&1 || die "terraform is not on PATH"
command -v aws >/dev/null 2>&1 || die "the AWS CLI is not on PATH"

trap cleanup EXIT
# Left over from an interrupted run: it would silently redirect this run's
# state to the local file.
rm -f "$OVERRIDE_FILE"

log "credentials"
aws sts get-caller-identity --output table ||
  die "no usable AWS credentials (set AWS_PROFILE, or configure a default profile)"
account_id="$(aws sts get-caller-identity --query Account --output text)"
state_bucket="coppice-terraform-state-$account_id"

tf_vars=(-var "region=$REGION" -var "domain=$DOMAIN")
if [ "$validate" = true ]; then
  tf_vars+=(-var "validate_certificate=true")
fi

apply_args=()
if [ "$auto_approve" = true ]; then
  apply_args+=(-auto-approve)
fi

local_state="$LOCAL_STATE_DIR/bootstrap.tfstate"
bucket_targets=(
  -target=aws_s3_bucket.state
  -target=aws_s3_bucket_versioning.state
  -target=aws_s3_bucket_server_side_encryption_configuration.state
  -target=aws_s3_bucket_public_access_block.state
  -target=aws_s3_bucket_lifecycle_configuration.state
)

# Move the local first-apply state into the bucket it created, then drop the
# local copy: left behind, it is a stale duplicate a later run could pick up.
migrate_local_state() {
  log "migrating state into s3://$state_bucket"
  write_local_backend_override
  terraform -chdir="$MODULE_DIR" init -input=false >/dev/null
  cleanup
  terraform_init_s3 -input=false -migrate-state -force-copy
  rm -rf "$LOCAL_STATE_DIR"
}

if ! state_bucket_exists "$state_bucket"; then
  # Chicken and egg: the stack's backend is a bucket the stack itself creates.
  # Create just the bucket against a local state file, then migrate that state
  # into the bucket. Only ever happens once per account.
  log "state bucket s3://$state_bucket does not exist; bootstrapping it locally"
  write_local_backend_override
  terraform -chdir="$MODULE_DIR" init -input=false

  if [ "$plan_only" = true ]; then
    log "plan (state bucket only; the rest cannot be planned before it exists)"
    terraform -chdir="$MODULE_DIR" plan -input=false "${bucket_targets[@]}" ${tf_vars[@]+"${tf_vars[@]}"}
    exit 0
  fi

  log "apply (state bucket only)"
  terraform -chdir="$MODULE_DIR" apply -input=false ${apply_args[@]+"${apply_args[@]}"} "${bucket_targets[@]}" ${tf_vars[@]+"${tf_vars[@]}"}
  migrate_local_state
elif [ -f "$local_state" ]; then
  # A previous run created the bucket and was interrupted before the
  # migration finished. The bucket's resources live only in this local file;
  # pointing Terraform at the (empty) remote state now would make it try to
  # create the bucket again. Finish the migration first.
  log "state bucket exists and $local_state survives from an interrupted run"
  migrate_local_state
else
  log "state bucket s3://$state_bucket already exists"
  # -reconfigure keeps this idempotent whatever the working directory last
  # pointed at, without ever offering to migrate.
  terraform_init_s3 -input=false -reconfigure

  # Once validation has been applied, keep it: a later run without --validate
  # would otherwise plan to destroy aws_acm_certificate_validation and flip
  # `certificate_validated` back to false for every env stack reading it.
  if [ "$validate" = false ] &&
    [ "$(terraform -chdir="$MODULE_DIR" output -raw certificate_validated 2>/dev/null)" = "true" ]; then
    log "certificate validation is already applied; keeping it"
    validate=true
    tf_vars+=(-var "validate_certificate=true")
  fi
fi

if [ "$plan_only" = true ]; then
  log "plan"
  terraform -chdir="$MODULE_DIR" plan -input=false ${tf_vars[@]+"${tf_vars[@]}"}
  exit 0
fi

log "apply"
terraform -chdir="$MODULE_DIR" apply -input=false ${apply_args[@]+"${apply_args[@]}"} ${tf_vars[@]+"${tf_vars[@]}"}

log "outputs"
terraform -chdir="$MODULE_DIR" output

if [ "$validate" = true ]; then
  # The apply above included aws_acm_certificate_validation, so reaching here
  # means ACM issued the certificate and environments can be brought up.
  log "wildcard certificate is issued; the account is ready for env stacks"
else
  echo
  echo "------------------------------------------------------------------"
  terraform -chdir="$MODULE_DIR" output -raw delegation_instructions
  echo
  echo "------------------------------------------------------------------"
fi
