//! proto3 JSON mapping for the public-API messages (ADR: JSON at the edge).
//!
//! These assertions pin the conventions the HTTP surface depends on:
//! camelCase field names, 64-bit ints rendered as JSON strings, unset
//! optionals omitted, and typed ids as their `<prefix>-<uuid>` string form
//! wrapped in `{ "value": ... }`. They are generated by pbjson-build from the
//! frozen descriptor set, so a drift here is a wire-contract change.

use coppice_proto::pb::api::v1::SubmitJobRequest;
use coppice_proto::pb::core::v1::{JobId, QuotaEntityId};

fn sample_request() -> SubmitJobRequest {
    SubmitJobRequest {
        image: "registry.example/app:1".to_string(),
        requests: None,
        priority: 5,
        // A value beyond 2^53 to prove it survives as a string, not an f64.
        max_runtime_us: Some(9_007_199_254_740_993),
        quota_entity: Some(QuotaEntityId {
            value: "quota-1683852a-993f-4497-a48b-6527b458fbd1".to_string(),
        }),
        retry: None,
        job: Some(JobId {
            value: "job-1683852a-993f-4497-a48b-6527b458fbd1".to_string(),
        }),
        command: vec!["/bin/run".to_string(), "--flag".to_string()],
        entrypoint: None,
    }
}

#[test]
fn serializes_with_proto3_json_conventions() {
    let req = sample_request();
    let json: serde_json::Value = serde_json::to_value(&req).expect("serialize");

    // camelCase field names (not the snake_case proto/Rust identifiers).
    assert!(json.get("maxRuntimeUs").is_some());
    assert!(json.get("max_runtime_us").is_none());
    assert!(json.get("quotaEntity").is_some());

    // 64-bit ints render as JSON strings, exact past the f64 mantissa limit.
    assert_eq!(json["maxRuntimeUs"], serde_json::json!("9007199254740993"));

    // Typed ids serialize as their `<prefix>-<uuid>` string, wrapped as the
    // JobId message's single `value` field.
    assert_eq!(
        json["job"]["value"],
        serde_json::json!("job-1683852a-993f-4497-a48b-6527b458fbd1")
    );

    // Unset optional message fields are omitted, not rendered as null.
    assert!(json.get("requests").is_none());
    assert!(json.get("retry").is_none());
    assert!(json.get("entrypoint").is_none());

    // Repeated scalar survives as a JSON array.
    assert_eq!(json["command"], serde_json::json!(["/bin/run", "--flag"]));
}

#[test]
fn round_trips_through_json() {
    let req = sample_request();
    let text = serde_json::to_string(&req).expect("serialize");
    let back: SubmitJobRequest = serde_json::from_str(&text).expect("deserialize");
    assert_eq!(req, back);
}

#[test]
fn deserializes_u64_string_and_camel_case() {
    // The mapping must accept the string form it emits for u64 fields.
    let json = r#"{
        "image": "registry.example/app:1",
        "priority": 5,
        "maxRuntimeUs": "9007199254740993",
        "job": { "value": "job-1683852a-993f-4497-a48b-6527b458fbd1" },
        "command": ["/bin/run"]
    }"#;
    let req: SubmitJobRequest = serde_json::from_str(json).expect("deserialize");
    assert_eq!(req.max_runtime_us, Some(9_007_199_254_740_993));
    assert_eq!(
        req.job.unwrap().value,
        "job-1683852a-993f-4497-a48b-6527b458fbd1"
    );
}
