//! # coppice-raft-net
//!
//! tonic client/server stubs for the coordinator↔coordinator Raft transport
//! and the membership admin surface (`coppice.raft.v1`, ADR 0002/0016).
//!
//! Message types are NOT generated here — they come from [`coppice_proto`]
//! (the single owner of the schema corpus, ADR 0003); this crate generates
//! only the service glue, with `extern_path` pointing every message at
//! `coppice_proto::pb`. The pb↔openraft conversions live in
//! `coppice-consensus` (`net` module and `storage/raftpb.rs`), keeping
//! openraft types out of this crate entirely.
//!
//! The generated code lives in [`pb`] (raw tonic module names); [`transport`]
//! and [`admin`] re-export the client, server, and server-trait types under
//! stable, readable aliases.

/// The raw tonic output for `coppice.raft.v1`: one client and one server
/// module per service, generated by `build.rs`. Message types resolve to
/// [`coppice_proto::pb::raft::v1`] via `extern_path`, so nothing here
/// redefines a schema type.
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/coppice.raft.v1.rs"));
}

/// The coordinator Raft transport service (`RaftTransportService`):
/// AppendEntries, Vote, and streaming InstallSnapshot (ADR 0002).
pub mod transport {
    pub use crate::pb::raft_transport_service_client::RaftTransportServiceClient as Client;
    pub use crate::pb::raft_transport_service_server::{
        RaftTransportService, RaftTransportServiceServer as Server,
    };
}

/// The membership admin service (`RaftAdminService`): add-learner,
/// promote-voter, remove-node, and cluster-status (ADR 0016).
pub mod admin {
    pub use crate::pb::raft_admin_service_client::RaftAdminServiceClient as Client;
    pub use crate::pb::raft_admin_service_server::{
        RaftAdminService, RaftAdminServiceServer as Server,
    };
}
