//! # coppice-agent-net
//!
//! tonic client/server stubs for the agent↔coordinator session transport
//! (`coppice.agent.v1.AgentService`, ADR 0009/0011).
//!
//! Message types are NOT generated here — they come from [`coppice_proto`]
//! (the single owner of the schema corpus, ADR 0003); this crate generates
//! only the service glue, with `extern_path` pointing every message at
//! `coppice_proto::pb`. The session semantics (fencing, registration,
//! reconciliation) live with the endpoints: the coordinator's agent gateway
//! and the agent's session loop.
//!
//! The generated code lives in [`pb`] (raw tonic module names); [`session`]
//! re-exports the client, server, and server-trait types under stable,
//! readable aliases.

/// The raw tonic output for `coppice.agent.v1`: one client and one server
/// module for `AgentService`, generated by `build.rs`. Message types resolve
/// to [`coppice_proto::pb::agent::v1`] via `extern_path`, so nothing here
/// redefines a schema type.
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/coppice.agent.v1.rs"));
}

/// The agent session service (`AgentService`): one long-lived bidirectional
/// stream per agent — reports up, commands down (ADR 0009).
pub mod session {
    pub use crate::pb::agent_service_client::AgentServiceClient as Client;
    pub use crate::pb::agent_service_server::{AgentService, AgentServiceServer as Server};
}
