/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoordinatorsRouteImport } from './routes/coordinators'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as NodesNodeIdRouteImport } from './routes/nodes.$nodeId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'

const CoordinatorsRoute = CoordinatorsRouteImport.update({
  id: '/coordinators',
  path: '/coordinators',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coordinators': typeof CoordinatorsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/nodes/': typeof NodesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coordinators': typeof CoordinatorsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/jobs': typeof JobsIndexRoute
  '/nodes': typeof NodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coordinators': typeof CoordinatorsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/nodes/': typeof NodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coordinators'
    | '/jobs/$jobId'
    | '/nodes/$nodeId'
    | '/jobs/'
    | '/nodes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coordinators'
    | '/jobs/$jobId'
    | '/nodes/$nodeId'
    | '/jobs'
    | '/nodes'
  id:
    | '__root__'
    | '/'
    | '/coordinators'
    | '/jobs/$jobId'
    | '/nodes/$nodeId'
    | '/jobs/'
    | '/nodes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoordinatorsRoute: typeof CoordinatorsRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  NodesIndexRoute: typeof NodesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coordinators': {
      id: '/coordinators'
      path: '/coordinators'
      fullPath: '/coordinators'
      preLoaderRoute: typeof CoordinatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoordinatorsRoute: CoordinatorsRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  NodesNodeIdRoute: NodesNodeIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  NodesIndexRoute: NodesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
